
security:
    oauth2:
        client:
            access-token-validity-seconds: 1800
            authorized-grant-types: password,refresh_token
            client-id: mastertoken
            client-secret: $2a$10$trmwjPUZG3Wf0shMm7L72u9g8A2QN8BL9AZlZ2uOx/vUA0eLmze4.
            resource-ids: resources
            scope: read,write
            
spring:
    datasource:
#        data: classpath:/sql/data.sql
        driver-class-name: org.postgresql.Driver
        username: lud
        password: 123456
        platform: postgresql
#        schema: classpath:/sql/schema.sql
        url: jdbc:postgresql://localhost:5432/auth_db
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: false
        hibernate:
            ddl-auto: none
        show-sql: true

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:7001}/eureka/

---
spring:
    profiles: heroku
    datasource:
        driver-class-name: org.postgresql.Driver
        username: ${JDBC_DATABASE_USERNAME}
        password: ${JDBC_DATABASE_PASSWORD}
        platform: postgresql
        url: ${JDBC_DATABASE_URL}
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: false
        hibernate:
            ddl-auto: none
        show-sql: true
eureka:
    instance:
        hostname: ${DOMAIN_NAME}:${$PORT}


#spring:
#    datasource:
#        data: classpath:/sql/data.sql
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        password: 'db-tcc-123'
#        platform: mysql
#        schema: classpath:/sql/schema.sql
#        url: jdbc:mysql://172.17.0.2:3306/db_oauth?verifyServerCertificate=false&useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
#        username: root
#    jpa:
#        database-platform: org.hibernate.dialect.MySQLDialect
#        generate-ddl: false
#        hibernate:
#            ddl-auto: none
#        show-sql: true

