zuul:
    ignored-services: '*'
    routes:
        catalog:
          url: ${CATALOG_URL:http://localhost:9001}
          sensitive-headers:
        customer:
          url: ${CUSTOMER_URL:http://localhost:8082}/customer
          sensitive-headers:
security:
  sessions: ALWAYS
  ignored:
  - "*.bundle.*"  

eureka:
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: ${EUREKA_URL:http://localhost:7001}/eureka/

---
spring:
  profiles: heroku
eureka:
  instance:
    hostname: ${DOMAIN_NAME}:${$PORT}
    