//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.21 at 07:06:34 PM BRST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ricardoludwig-quotation.com.br/web-service", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package br.com.ricardoludwig_quotation.web_service;
